[book]
title = "Persona Exporter"
authors = ["0DoubleDare"]
language = "en"
text-direction = "ltr"

[output.html]
git-repository-url = "https://github.com/Persona-Team/persona-exporter-docs"
additional-js = ["mermaid.min.js", "mermaid-init.js", "theme/tabs.js"]
additional-css = ["src/custom.css", "theme/tabs.css"]
sidebar-header-nav = false

[output.html.redirect]
"/3_configuration/" = "/configuration/"
[preprocessor]

[preprocessor.tabs]
command = "mdbook-tabs"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.numbering]
#code-block = true
code = { enable = false }
heading = { enable = false }

